name: Windows Cygwin

on: [push, pull_request]

env:
  PATH: 'C:\tools\cygwin\bin;C:\Program Files\Git\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0;C:\ProgramData\Chocolatey\bin'
  FORCE_COLOR: 1

defaults:
  run:
    shell: cmd

jobs:
  windows-cygwin:
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    # https://github.com/actions/runner-images/blob/-/images/windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        shell:
          - sh
          - dash
          - bash
          - ash
          - mksh
          - posh
          - zsh
    steps:
      - uses: actions/checkout@v6
      - run: choco install --yes --no-progress cygwin cyg-get
      - run: cyg-get nc '${{ case(matrix.shell == 'ash', 'busybox', matrix.shell) }}'
      - run: cygcheck -c
      - run: env '${{ matrix.shell }}' ./shellspec --task fixture:stat:prepare
      - run: env '${{ matrix.shell }}' -c "rm helper/fixture/stat/no-permission"
      - run: env '${{ matrix.shell }}' ./shellspec
